checkboxlisttile
kimhk0203/todolist01 pull request #7
Opened 2023-03-15 12:40 UTC by kimhk0203

チェックボックスを取り入れた。

2023-03-18 01:49 UTC, kimhk0203 commented
flutterのアイコン変更（アンドロイド）

2023-03-18 01:54 UTC, kimhk0203 commented
flutterのアイコン変更（IOS）

2023-03-18 01:58 UTC, dai10512 commented
iOSしか見てないけど、アイコンが反映されてないね 👀 

https://user-images.githubusercontent.com/38497198/226077310-9633c645-e1df-4ce9-b3bf-1ed272d77ac7.mp4

2023-03-18 02:00 UTC, dai10512 commented
こうゆう状態かな
- 画像を生成する　済
- 画像をアイコンに適用させる　未

pubspec.yamlに書き足してないからだと思う 🤔 
https://pub.dev/packages/flutter_launcher_icons

2023-03-20 05:49 UTC, dai10512 commented
@kimhk0203 こっちは削除する？

2023-03-20 06:01 UTC, dai10512 commented
@kimhk0203 アイコン画像が出るように修正しよう 🙋‍♂️

2023-03-20 06:01 UTC, dai10512 requested changes
@kimhk0203 アイコン画像が出るように修正しよう 🙋‍♂️

2023-03-20 14:52 UTC, kimhk0203 commented
> @kimhk0203 アプリのアイコン画像が出るように修正しよう 🙋‍♂️

これもなんか変なの触ったのかな、、pubspec.yaml　足したけどIOSのところがエラーになる。
アプリのアイコンの画像を入れる前の状態に戻せないかな？
もう一度やり直したいんだけど

2023-03-21 04:19 UTC, kimhk0203 commented
@dai10512 これって修正前に戻せる？もう一度やり直したいんだけど

2023-03-21 06:43 UTC, dai10512 commented
修正前か。。

2023-03-21 06:44 UTC, dai10512 commented
その前に原因確認した方がいいと思う

2023-03-21 06:48 UTC, dai10512 commented
pubspec.yaml書いてないんじゃない？

2023-03-22 06:52 UTC, kimhk0203 commented
書いたよ。書いたけどよくわからなくてネットで調べて他の方法でファイルから直接イメージ入れてたから、それがなんかエラーになってるのかなあと。でも修正方法がよくわからん。、 @dai10512

2023-03-22 11:34 UTC, dai10512 commented
でもこのページにpubspeck.yamlないよ？ってことは、変更してないんじゃない？

分からないことがあったら、ここにコミットして、その時点で聞くのがいいよ


https://github.com/kimhk0203/todolist01/pull/7/files

2023-03-22 11:36 UTC, dai10512 commented on lib/main.dart
> -                fontStyle: FontStyle.italic,
ここにコメント入れる

2023-03-22 11:38 UTC, dai10512 commented
分からない箇所は、こうやってコードにコメントを入れると、レビューする人がわかりやすいよ 🤚 
https://user-images.githubusercontent.com/38497198/226892760-615b0870-862c-444b-b45f-12f169bfe474.mov

2023-03-23 14:25 UTC, dai10512 commented
どっちのプルリクを見ればいいんだ。。。

2023-03-23 14:28 UTC, dai10512 commented
.yamlの修正はこっちで行おう。

2023-03-23 14:38 UTC, dai10512 commented
[画面収録 2023-03-23 23.33.10.mov.zip](https://github.com/kimhk0203/todolist01/files/11052122/2023-03-23.23.33.10.mov.zip)

2023-03-23 14:39 UTC, dai10512 commented
作った.yamlのブランチを、ローカルでchekboxlisttileのブランチにくっつけよう。

2023-03-27 13:36 UTC, merged