Delete
kimhk0203/todolist01 pull request #8
Opened 2023-03-19 14:10 UTC by kimhk0203

削除ボタンがなかったので追加

2023-03-20 05:59 UTC, dai10512 commented
削除ボタンある？

![simulator_screenshot_1A239CF8-1B40-49FA-BC69-E99182F686BC](https://user-images.githubusercontent.com/38497198/226259249-e28e8185-085b-4e3b-bb49-e14455fa10ca.png)

2023-03-20 06:03 UTC, dai10512 commented
deleteブランチはcheckBoxListブランチからfolk（派生）してるため、checkBoxListをマージ先に変更

2023-03-20 06:04 UTC, dai10512 requested changes
@kimhk0203 
削除アイコンが入ってないと思うので、要確認 🙄

2023-03-20 14:48 UTC, kimhk0203 commented
> @kimhk0203 削除アイコンが入ってないと思うので、要確認 🙄
スワイプ式なの。削除アイコン入れたかったけど入れられない。なんか色々修正しなきゃいけないみたい。。

2023-03-20 23:43 UTC, dai10512 commented
まだ作業中ってこと？スライド式で削除する機能に変更したってこと？

もし作業中だったら、draftに変更しておいて。
レビューをお願いするなら、どう変更したか、スクショもできれば添付して 🙋‍♂️ 


<img width="291" alt="スクリーンショット 2023-03-21 8 41 52" src="https://user-images.githubusercontent.com/38497198/226488807-164a1345-0300-4495-ae9b-cf27388eec78.png">

2023-03-20 23:44 UTC, dai10512 commented
削除ボタンじゃなくてスライドの削除機能なのね。確認する 🙋‍♂️

2023-03-21 04:09 UTC, dai10512 approved these changes

2023-03-21 04:09 UTC, dai10512 commented
とりあえず削除は確認済み
LGTM

2023-03-21 06:43 UTC, dai10512 commented
approveしてるから、mergeしちゃって

2023-03-23 12:52 UTC, merged